# Configuration Garlic.iaas.dbz
---
- hosts: all

  tasks:
    - user:
        name: iaas
        uid: 1000
        group: wheel
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_type: rsa
        ssh_key_file: .ssh/id_rsa
       tags: generate_ssh       
   
    - name: 0.1 - Mise à jour des packages
      yum: name=* state=latest
      tags: update

    - name: 0.2 - Récuperation d'omzsh pour iaas
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      become: yes
      become_user: iaas
      tags: omzsh

    - name: 0.3 - Config du theme pour iaas
      shell: sh -c "$(sed -i '10s/ZSH_THEME="robbyrussell"/ZSH_THEME="gentoo"/' /home/iaas/.zshrc)"
      become: yes
      become_user: iaas
      tags: omzsh

    - name: 0.4 - Récuperation d'omzsh pour root
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      become: yes
      become_user: root
      tags: omzsh

    - name: 0.5 - Config du theme pour root
      shell: sh -c "$(sed -i '10s/ZSH_THEME="robbyrussell"/ZSH_THEME="gentoo"/' /root/.zshrc)"
      become: yes
      become_user: root
      tags: omzsh
    
    - name: 0.6 - Installation de Docker
      shell: |
        curl -fsSL https://get.docker.com/ | sh
        usermod -aG docker iaas
        systemctl start docker
        systemctl enable docker
      tags: docker_install

- hosts: master

  tasks:
    - name: 0.7 - Changement du nom d'hote garlic
      shell: |
        sh -c "$(> /etc/hostname)"
        echo "garlic.iaas.dbz" > /etc/hostname
      tags: hostname_master
        
    - name: 0.8 - Initialisation du cluster Swarm et récupération du token worker (/home/iaas/token)
      shell: |
        docker swarm init --advertise-addr 10.0.255.245
        docker swarm join-token worker -q > /home/iaas/token
      tags: init_swarm

    - name: 0.9 - Ouverture des port du pare-feu
      shell: |
        firewall-cmd --zone=public --add-port=2377/tcp --permanent
        firewall-cmd --zone=public --add-port=7946/tcp --permanent
        firewall-cmd --zone=public --add-port=7946/udp --permanent
        firewall-cmd --zone=public --add-port=4789/udp --permanent
        firewall-cmd --reload
      tags: firewall_rules

    - name: 1.0 - Envoi du token au workers
      shell: |
        ssh-copy-id -o "StrictHostKeyChecking no" -f -i /home/iaas/.ssh/id_rsa.pub iaas@10.0.255.246
        scp /home/iaas/token iaas@10.0.255.246:/home/iaas/token
        ssh-copy-id -o "StrictHostKeyChecking no" -f -i /home/iaas/.ssh/id_rsa.pub iaas@10.0.255.247
        scp /home/iaas/token iaas@10.0.255.247:/home/iaas/token
      become: yes
      become_user: iaas
      tags: send_token

- hosts: nodes[0]

  tasks:
    - name: 2.0 - Changement du nom d'hote janemba
      shell: |
        sh -c "$(> /etc/hostname)"
        echo "janemba.iaas.dbz" > /etc/hostname
      tags: hostname_node1  

    - name: 2.1. Récupération du token worker et join le cluster swarm (/home/iaas/token)
      shell: |
        token=$(cat /home/iaas/token)
        docker swarm join --token $token 10.0.255.245:2377
      become: yes
      become_user: iaas
      tags: join_worker_1

- hosts: nodes[1]

  tasks:
    - name: 3.0 - Changement du nom d'hote dabra
      shell: |
        sh -c "$(> /etc/hostname)"
        echo "dabra.iaas.dbz" > /etc/hostname
      tags: hostname_node2
    
    - name: 3.1. Récupération du token worker et join le cluster swarm (/home/iaas/token)
      shell: |
        token=$(cat /home/iaas/token)
        docker swarm join --token $token 10.0.255.245:2377
      become: yes
      become_user: iaas
      tags: join_worker_2 