---
- name: 1 - Vérification si EPEL repo est déjà installé
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result
 
- name: 2 - Installation du repo EPEL
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
 
- name: 3 - Import de la clé GPG EPEL
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists