- user:
    name: iaas
    password: iabHW9z84FPuI
    uid: 1000
    group: wheel
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    ssh_key_file: .ssh/id_rsa

- name: 0.2 - Mise à jour des packages
  yum: name=* state=latest

- name: Verification de l'installation de Docker
  shell: docker ps
  register: docker_result
  failed_when: "'FAILED' in docker_result.stderr"
  tags: docker_check

- name: Installation de Docker
  yum: state=present name=docker
  when:
      - ansible_distribution == "CentOS"
      - ansible_distribution_major_version == "7"
      - docker_result|failed
  tags: docker_check 

- name: 0.6 - Installation de Docker
  shell: |
    curl -fsSL https://get.docker.com/ | sh
    usermod -aG docker iaas
    systemctl start docker
    systemctl enable docker
  tags: docker_install 